### ISSUE TITLE
Use with Monk Active Tiles

### ISSUE THREAD

**Issue by gubacelar** [brunocalado/wheel-of-destiny#3]
There is any chance to change the macro, and let pass the list to be selected as a param?
So it can be used in Monk Active Tiles for traps.

**Comment by brunocalado** [comment]
> There is any chance to change the macro, and let pass the list to be selected as a param? So it can be used in Monk Active Tiles for traps.

Do you have an example?

I can make the macro accept params and return a token. Is that it?

**Comment by gubacelar** [comment]
Yes, just like that.

**Comment by gubacelar** [comment]
With monk active tiles, if a token enter on a tile, I can activate a macro and get this result to make something.

**Comment by brunocalado** [comment]
> With monk active tiles, if a token enter on a tile, I can activate a macro and get this result to make something.

the params can be one []? 
the return can be the token object?

**Comment by gubacelar** [comment]
yes, it would be great and array of tokens and the "choosen" token as a return.

**Comment by brunocalado** [comment]
update
